[package]
name = "_03-types-variables"
version = "0.1.0"
authors = ["augustine <augustino0890@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
